name: JavaScript CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - name: Install dependencies
              run: npm install
            - name: Run linters
              run: |
                  npx eslint .
                  npx prettier --check .
            - name: Run tests
              run: npm test itemController
